### ISSUE TITLE
implementation 'com.kongzue.dialog:dialog:2.2.9.5' 使用有问题

### ISSUE THREAD

**Issue by m511386374** [kongzue/Dialog#10]
这个在安卓5.0红米2上使用WaitDialog.show(this,"222222").showDialog(); 异常提示 
08-23 11:21:22.714 8091-8091/www.goodycom.com.newglgs:error_activity E/CustomActivityOnCrash: The previous app process crashed. This is the stack trace of the crash:
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4011)
        at android.view.ViewGroup.addView(ViewGroup.java:3864)
        at com.kongzue.dialog.v2.WaitDialog$1.run(WaitDialog.java:113)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5562)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
但是使用SelectDialog.show(this, "提示", "请做出你的选择", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {

            }
        }); 
而且在当 DialogSettings.type = TYPE_IOS; 使用这个Style的时候必须要配置这个属性 renderscriptTargetApi 19
        renderscriptSupportModeEnabled true  
虽然我没有使用模糊属性
但是在安卓6.0华为上面可以正常使用.

**Comment by kongzue** [comment]
您好，
关于问题1，主要是因为View被复用，没有被卸载导致的，此问题会在下一版本进行修复。
关于问题2，文档中有说明，请使用DialogSettings.use_blur = false;关闭模糊效果；
