### ISSUE TITLE
弹出弹窗前切换其他APP，然后切回，必然会出一个错误

### ISSUE THREAD

**Issue by xvalerian** [kongzue/Dialog#22]
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1033)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1000)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:950)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:911)
        at com.kongzue.dialog.util.BlurView.drawBlurredBitmap(BlurView.java:354)
        at com.kongzue.dialog.util.BlurView.onDraw(BlurView.java:330)
        at android.view.View.draw(View.java:20261)
        at com.kongzue.dialog.util.BlurView.draw(BlurView.java:323)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at com.android.internal.policy.DecorView.draw(DecorView.java:801)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3406)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3179)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2548)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7388)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1062)
        at android.view.Choreographer.doCallbacks(Choreographer.java:874)
        at android.view.Choreographer.doFrame(Choreographer.java:805)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by kongzue** [comment]
你这是干了啥......

**Comment by kongzue** [comment]
我这里怎么测试都没重现这个问题啊

**Comment by xvalerian** [comment]
> 你这是干了啥......

比如说请求网络数据，请求完成后会弹出一个提示框，但是我请求完成前切换到了其他APP，然后大概等他弹出后再切回自己的APP，Activity显示的那一瞬间就报这个错闪退，我bugly统计的用户数据，大部分都是报这个错

**Comment by kongzue** [comment]
主要是我这边也很常用这个框架，在很多应用中都有使用，但从来没有出现过这个问题，所以对此感到很奇怪

**Comment by kongzue** [comment]
也没有收到任何其他用户反馈用样的问题...您可以告知您的测试手机以及主要是用哪个组件出现此情况的么？

**Comment by xvalerian** [comment]
> 也没有收到任何其他用户反馈用样的问题...您可以告知您的测试手机以及主要是用哪个组件出现此情况的么？

我bugly上看了，出错机型基本覆盖了所有手机厂商和Android 版本，出错最多的是Android 8.1

**Comment by xvalerian** [comment]
> 奇怪的是我这边以及其他使用Dialog组件的用户都没有报告出现过此问题，且BlurView的宽高是MATCH_PARENT的，不可能小于0（具体请参照MessageDialog的284行代码）。如果您不需要使用模糊效果可以通过DialogSettings.use_blur = false;来关闭，关闭后不会再调用BlurView了。目前尚无法确定导致此问题的原因，不过我已记录，感谢您的反馈

感谢您的耐心回复，我刚刚试了一下Android studio的Android 8.1.0 api27  x86的虚拟机也复现了这个bug。不知道可不可以判断一下这个MATCH_PARENT，当等于0时可以设置他为1。模糊效果的话非常好看，有点不舍得放弃

**Comment by xvalerian** [comment]
> 新版本已修改blurView

好的，我测试了一下
会报以下错误，
场景：打开app加载网络数据大概3秒后弹出对话框
复现步骤为： 打开app后，马上切回桌面，然后大概等他弹出对话框之后再切回app，然后就会报以下错误然后闪退
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:61)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:79)
        at com.kongzue.dialog.util.BlurView.drawBlurredBitmap(BlurView.java:367)
        at com.kongzue.dialog.util.BlurView.onDraw(BlurView.java:333)
        at android.view.View.draw(View.java:20261)
        at com.kongzue.dialog.util.BlurView.draw(BlurView.java:326)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.View.draw(View.java:19989)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
        at android.view.View.draw(View.java:20264)
        at com.android.internal.policy.DecorView.draw(DecorView.java:801)
        at android.view.View.updateDisplayListIfDirty(View.java:19136)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3406)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3179)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2548)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1523)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7395)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1065)
        at android.view.Choreographer.doCallbacks(Choreographer.java:877)
        at android.view.Choreographer.doFrame(Choreographer.java:808)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1051)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

BlurView.java:367定位到以下代码
canvas.drawBitmap(mRoundBitmap, 0, 0, mPaint);

**Comment by David-chen1** [comment]
> 新版本已修改blurView

请问这个问题在最新版本上修复了吗  我用的2.4.7版本也复现了这个Bug
