### ISSUE TITLE
java.lang.Throwable: loadSystemProperties

### ISSUE THREAD

**Issue by Jay-YaoJie** [kongzue/Dialog#29]
customDialog = CustomDialog.show(getActivity(), R.layout.window_scan_device, new CustomDialog.BindView() 
这一行引起以下错误

 java.lang.Throwable: loadSystemProperties
        at android.view.ThreadedRenderer.loadSystemProperties(ThreadedRenderer.java:262)
        at android.view.ThreadedRenderer.<init>(ThreadedRenderer.java:130)
        at android.view.HardwareRenderer.create(HardwareRenderer.java:428)
        at android.view.ViewRootImpl.enableHardwareAcceleration(ViewRootImpl.java:883)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:595)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:342)
        at com.kongzue.dialog.v2.CustomDialog.showDialog(CustomDialog.java:98)
        at com.kongzue.dialog.v2.CustomDialog.show(CustomDialog.java:42)
        at com.things.kiwy.bletooths.HomeBFragment$2.onItemClick(HomeBFragment.java:138)

**Comment by kongzue** [comment]
目前无法确定此问题的原因，我这里也尚未收到任何其他关于此问题的报告。稍后我会查询相关资料确定此问题的原因。
