### ISSUE TITLE
 DialogSettings.type = DialogSettings.TYPE_IOS; //用这个款式会崩

### ISSUE THREAD

**Issue by kingofalpha** [kongzue/Dialog#37]
DialogSettings.type = DialogSettings.TYPE_IOS; //用这个款式会崩
                                SelectDialog.show(getActivity(), Language.warning_title, temp_warning, Language.dialog_for_edit_file_input_1_button_ok_title, new DialogInterface.OnClickListener() {
                                    @Override
                                    public void onClick(DialogInterface dialog, int which) {

                                    }
                                }, Language.dialog_for_edit_file_input_1_button_no_title, new DialogInterface.OnClickListener() {
                                    @Override
                                    public void onClick(DialogInterface dialog, int which) {
                                        
                                    }
                                });

**Comment by kingofalpha** [comment]
12-18 13:35:40.484 1354-2213/? W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.NullPointerException
        at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
        at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)

我感觉是在这里有问题 ，demo版没有任何问题

**Comment by kongzue** [comment]
您好，您给出的日志里没有包含“com.kongzue.dialog”子包下任何类中的错误信息，我无法确定是KongzueDialog库的问题，如果需要排查KongzueDialog库的问题，请提供包含“com.kongzue.dialog”子包的错误信息

**Comment by kingofalpha** [comment]
12-18 13:44:28.279 26750-26750/cn.com.bai.contorl_glt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.com.bai.contorl_glt, PID: 26750
    java.lang.VerifyError: com/kongzue/dialog/util/BlurView   //你要的是这行日志吗
        at com.kongzue.dialog.v2.SelectDialog$6.run(SelectDialog.java:342)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5016)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by kongzue** [comment]
正在排查

**Comment by kingofalpha** [comment]
好的，谢谢作者

**Comment by kongzue** [comment]
因为无法查询到具体的原因，SelectDialog.java:342行的代码是创建BlurView的代码，但未见到任何类似的问题上报，现根据您提供的日志我无法排查到具体错误原因，因此此问题暂时无法解决。
请您先尝试禁用模糊效果即可正常使用。

禁用模糊效果的办法：
DialogSettings.use_blur = false;

**Comment by kingofalpha** [comment]
好的 感谢！
